'use client';

import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import ReduxProvider from './store/reduxProvider'
import { useEffect } from 'react'
// import { initializeSocket } from './socket'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Inklusive Task',
//   description: 'Generated by create next app',
// }

export default function RootLayout({children}: {children: React.ReactNode}) {
  
  // useEffect(() => {
  //   let socket = initializeSocket();
  //   console.log(socket);
  // }, []);

  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
